---
title: "Initial EDA for BNP Paribas Cardif Competition"
author: "Jim Thompson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
library(tidyr)
library(knitr)
library(Hmisc)
library(ggplot2)
library(plyr)
library(data.table)
library(Boruta)

# specify attributes used for identifying observations and response
ID.VAR <- "ID"
TARGET.VAR <- "target"

DATA.DIR <- "../data"
```


Load up the data
```{r}

load(file=paste0(DATA.DIR,"/train_calib_test.RData"))

# delete the calibration and test data sets
rm(calib.raw,test.raw)

# combine only the training data
train.raw <- rbind(train0.raw,train1.raw)
```

Determine attribute types found in data set
```{r}
# extract only candidate feture names
candidate.features <- setdiff(names(train.raw),c(ID.VAR,TARGET.VAR))
data.type <- sapply(candidate.features,function(x){class(train.raw[[x]])})
table(data.type)

print(data.type)

# deterimine data types
explanatory.attributes <- setdiff(names(train.raw),c(ID.VAR,TARGET.VAR))
data.classes <- sapply(explanatory.attributes,function(x){class(train.raw[[x]])})

# categorize data types in the data set?
unique.classes <- unique(data.classes)

attr.data.types <- lapply(unique.classes,function(x){names(data.classes[data.classes==x])})
names(attr.data.types) <- unique.classes
comment(attr.data.types) <- "list that categorize training data types"

# find numeric attributes that contain missing values
num.missing <- sapply(c(attr.data.types$numeric,attr.data.types$integer),
                      function(x){sum(is.na(train.raw[[x]]))})
attr.data.types$contain.na <- names(num.missing)[num.missing>0]
save(attr.data.types,file=paste0(DATA.DIR,"/attr_data_types.RData"))

# create synthetic features for analyis
# retrieve Boruta analysis results
load(paste0(DATA.DIR,"/boruta_feature_analysis.RData"))

important.vars <- getSelectedAttributes(bor.results)

# count missing values for all attributes and those deemed important by Boruta
all.var.na.count <- apply(train.raw,1,function(row){sum(is.na(row))})
imp.var.na.count <- apply(train.raw[,important.vars,with=FALSE],1,function(row){sum(is.na(row))})

train.raw <- cbind(train.raw,all.var.na.count,imp.var.na.count)

```

Initial summary look at the variables
```{r}
cat("Number of observations:",nrow(train.raw),", number complete obserations:",nrow(na.omit(train.raw)),
    ", pct complete:",100*nrow(na.omit(train.raw))/nrow(train.raw),"\n")

cat("Data types found in training data:\n")
attr.data.types

# summary stats
cat("distribution of target:\n")
table(train.raw$target)/nrow(train.raw)
summary(train.raw[,c(candidate.features,"all.var.na.count","imp.var.na.count"),with=FALSE])
```

Density plot
```{r fig.height=34,fig.width=8}
# convert to long format 
predictor.vars <- names(data.type[data.type=="numeric" | data.type=="integer"])
predictor.vars <- c(predictor.vars,"all.var.na.count","imp.var.na.count")
df <- gather(train.raw[,c(predictor.vars,"ID","target"),with=FALSE], feature, value, one_of(predictor.vars))

ggplot(df) + 
    geom_density(aes(x=value, colour=factor(target))) +
    facet_wrap(~feature,ncol=4,scales="free") 
```

